if(NOT DEFINED HEADER)
  message(FATAL_ERROR "HEADER is required")
endif()
if(NOT DEFINED NEEDLE)
  message(FATAL_ERROR "NEEDLE is required")
endif()
if(NOT EXISTS "${HEADER}")
  message(FATAL_ERROR "Missing required header: ${HEADER}")
endif()

file(READ "${HEADER}" _contents)
string(FIND "${_contents}" "${NEEDLE}" _found_at)
if(_found_at EQUAL -1)
  message(FATAL_ERROR "Header ${HEADER} does not contain required text: ${NEEDLE}")
endif()
